import type { Metadata } from "next";
import './assets/index.scss';
import "./globals.css";
import '@mantine/core/styles.css';
import {Header} from "@/app/components/Header";

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import {urbanistFonts} from "@/app/fonts";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en"  className={`${urbanistFonts.variable}`}>
      <head>
          <meta charSet="utf-8" />
          <meta
              name="viewport"
              content="minimum-scale=1, initial-scale=1, width=device-width"
          />
          <link rel="shortcut icon" href="/favicon.ico" />
        <ColorSchemeScript />
      </head>
      <body>
      <MantineProvider>
          <Header />
          {children}
      </MantineProvider>
      </body>
      </html>
  );
}
