name: prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script:
            export NVM_DIR=~/.nvm
            source ~/.nvm/svm.sh
            node -v
            cd ~/next-project
            git pull origin main
            yarn install
            yarn build
            kill -9 `lsof -t -i:80`
            yarn start & bg